const TOPICS = [
{id:'historia',name:'Livets historia',icon:'◷',color:'sand',pages:'Elevboken s. 10–11',intro:'Från de första cellerna till livet på land.',cards:[
['Allt börjar med celler','Jorden bildades för ungefär <b>4,6 miljarder år sedan</b>. De första livsformerna var encelliga och levde i vatten. I bokens tidslinje anges ungefär <b>3,5 miljarder år sedan</b>. Exakt hur livet uppstod vet forskarna ännu inte.','En cell är den minsta levande byggstenen. En bakterie består av en enda cell och saknar cellkärna.'],
['Fotosyntesen förändrade jorden','Vissa tidiga bakterier utvecklade fotosyntes. De använde ljus för att tillverka näring och släppte ut <b>syre</b>. Med tiden ökade syret i hav och luft. Det öppnade möjligheter för fler livsformer.','Solljus + vatten + koldioxid → druvsocker + syre. Ljuset ger energi; syret bildas vid processen.'],
['Livet blir mer varierat','Efter encelligt liv utvecklades flercelliga organismer. <b>Svampdjur och nässeldjur</b> hör till tidiga djurgrupper i havet. Maneter och koraller är nässeldjur. Svampdjur filtrerar vatten för att få föda.','Toffeldjur är encelliga organismer. Trots namnet räknas de inte som djur i modern indelning.'],
['Från vatten till land','Först kom enkla växter på land, bland annat mossliknande växter. Sedan följde djur. Tidiga landlevande leddjur tog upp syre genom <b>små öppningar och rör</b>. Från fiskliknande förfäder utvecklades så småningom fyrbenta ryggradsdjur.','Ordningen är viktigare än att kunna varje årtal: celler i vatten → fotosyntes och mer syre → flercelligt liv → växter och djur på land.'],
['Dinosaurier och däggdjur','Tidiga däggdjur levde samtidigt som dinosaurierna. Däggdjur har päls eller hår och ungar som <b>diar</b> mjölk. När de stora, icke-flygande dinosaurierna dog ut för cirka <b>66 miljoner år sedan</b> kunde däggdjuren spridas till fler livsmiljöer.','Fåglar är de dinosaurier som lever kvar. Vår art, Homo sapiens, uppstod långt senare: för ungefär 300 000 år sedan.']
]},
{id:'evolution',name:'Evolution & urval',icon:'↗',color:'mint',pages:'Elevboken s. 12–13',intro:'Hur ärftliga egenskaper förändras över generationer.',cards:[
['Vad är evolution?','<b>Evolution</b> betyder att ärftliga egenskaper hos grupper av organismer förändras över generationer. Stora förändringar tar ofta mycket lång tid. Till slut kan nya arter uppstå.','En individ som tränar och blir starkare är inte ett exempel på evolution. Evolution handlar om förändringar mellan generationer.'],
['Variation är råmaterialet','Individer inom samma art är olika. De kan till exempel ha olika färg, näbbform eller tålighet mot kyla. Det kallas <b>variation</b>. Ärftlig variation gör att det finns olika egenskaper som naturligt urval kan verka på.','Om miljön förändras kan en egenskap som tidigare var ovanlig bli en fördel.'],
['Naturligt urval – fyra steg','<b>1.</b> Individer har olika ärftliga egenskaper.<br><b>2.</b> Några egenskaper ger en fördel i den aktuella miljön.<br><b>3.</b> Individer med fördelen får oftare ungar som själva överlever och förökar sig.<br><b>4.</b> Egenskapen blir vanligare under många generationer.','Bäst anpassad betyder inte alltid starkast. Det kan handla om att vara väl kamouflerad, tåla kyla eller hitta rätt mat.'],
['Darwins finkar','<b>Charles Darwin</b> är känd för teorin om evolution genom naturligt urval. Finkar på olika öar hade olika näbbar. Kraftiga näbbar kunde knäcka hårda frön; smalare näbbar passade för att plocka insekter.','Finkarna hade gemensamma förfäder. Olika föda och miljöer bidrog till att olika näbbformer blev vanliga.'],
['Valen och hästen','Valarnas förfäder var fyrbenta landdjur. Över många generationer blev frambenen fenor, bakbenen mindre och näsborrarnas läge flyttades uppåt. Hästdjur utvecklade bland annat längre ben och tänder som passade för gräs.','Djuren bestämde sig inte för att förändras. Individer med användbara ärftliga egenskaper fick oftare avkomma.'],
['Förklara med ett exempel','Tänk att en fågelart lever där det blir kallare. Fåglar som redan har ärftliga egenskaper som hjälper dem att klara kylan kan få fler överlevande ungar. Efter många generationer kan dessa egenskaper vara vanligare.','Säg: ”Egenskapen blir vanligare över generationer.” Undvik: ”Fågeln vill ha tjockare fjädrar och får det.”']
]},
{id:'dna',name:'DNA & spår av liv',icon:'⌁',color:'lavender',pages:'Elevboken s. 14–15',intro:'Arv, mutationer, fossil och kol-14.',cards:[
['DNA, gener och arv','<b>DNA</b> bär organismens ärftliga information. En <b>gen</b> är en del av DNA som bidrar till egenskaper och funktioner. Vid könlig fortplantning kommer arvsmassa från både ägget och spermien.','Syskon får olika kombinationer av föräldrarnas gener. Därför kan de vara olika trots samma föräldrar.'],
['Mutation och avel','En <b>mutation</b> är en förändring i DNA. Den kan vara neutral, skadlig eller ibland ge en fördel. Den uppstår inte för att organismen behöver den. Vid <b>avel</b> väljer människor vilka djur eller växter som ska föröka sig för att få vissa egenskaper.','Naturligt urval: miljön påverkar vilka som får flest överlevande ungar. Avel: människor väljer föräldrar.'],
['DNA som ledtråd','Forskarna jämför DNA för att undersöka släktskap. Likheter kan tyda på gemensamma förfäder. Polisen kan jämföra DNA från biologiska spår, till exempel blod eller saliv, med prov från personer.','Ett vanligt fingeravtryck visar ett hudmönster. DNA-analys undersöker arvsmassan i biologiskt material.'],
['Vad berättar fossil?','<b>Fossil</b> är bevarade rester eller spår av äldre liv, till exempel förstenade ben eller avtryck. De visar hur organismer såg ut och hur livet har förändrats. I is kan ibland även mjukdelar bevaras.','Fossil och DNA kompletterar varandra: fossil visar bland annat kroppsformer, DNA hjälper oss att förstå släktskap.'],
['Kol-14 är en klocka','Levande organismer tar in kol. Efter döden upphör intaget och mängden radioaktivt <b>kol-14 minskar</b>. Efter cirka <b>5 730 år</b> återstår hälften. Mängden som finns kvar kan användas för att uppskatta åldern på organiskt material.','Metoden används upp till ungefär 50 000 år. I äldre material finns för lite kol-14 för säker mätning. Dinosauriefossil dateras med andra metoder.'],
['Mammuten','Människor och mammutar levde samtidigt. De allra sista mammutarna dog ut för ungefär <b>4 000 år sedan</b>. Förändrat klimat och människans jakt är viktiga förklaringar till mammutarnas tillbakagång.','Alla mammutar dog inte ut samtidigt. De flesta populationerna försvann långt före de sista på isolerade öar.']
]},
{id:'anpassning',name:'Anpassningar',icon:'❋',color:'peach',pages:'Elevboken s. 16–19',intro:'Kroppar och beteenden som hjälper arter att klara sig.',cards:[
['Form som passar miljön','En <b>anpassning</b> är en egenskap som hjälper en organism att klara sin miljö. Gäddan och tumlaren har strömlinjeformade kroppar som minskar vattenmotståndet. Stjärt och fenor hjälper dem att simma.','Gräsandens simfötter fungerar som paddlar. Näckrosens långa stjälkar och luftkanaler hjälper bladen att nå ljuset vid ytan.'],
['Olika sätt att andas','Fiskar tar upp löst syre ur vattnet med <b>gälar</b>. Många landlevande ryggradsdjur använder <b>lungor</b>. Vissa groddjur kan också ta upp syre genom huden.','Tumlaren och sälen är däggdjur med lungor. De måste upp till ytan för att andas luft.'],
['Skydd och kamouflage','Kamouflage gör ett djur svårt att upptäcka: en bönsyrsa kan likna ett blad och en hare kan ha vit vinterpäls. Andra djur skyddar sig med taggar, gift eller starka varningsfärger.','En färg är bara bra kamouflage i rätt omgivning. Vitt syns tydligt mot mörk mark men dåligt mot snö.'],
['Värme och vinter','Hos <b>växelvarma</b> djur, som grodor och många fiskar, påverkas kroppstemperaturen mycket av omgivningen. De blir ofta mindre aktiva i kyla. <b>Jämnvarma</b> fåglar och däggdjur håller en relativt jämn kroppstemperatur.','Vinterstrategier: tjock päls, flytt till varmare områden, dvala eller minskad aktivitet. Lövträd fäller bladen, vilket minskar vattenförlusten under vintern.'],
['Mat formar anpassningar','Korsnäbbens korsade näbb hjälper den att öppna kottar. Sädesärlans smala näbb passar för insekter. Lejon jagar ofta tillsammans; tigern smyger vanligtvis ensam och dess ränder ger kamouflage.','Köttätande växter får extra näringsämnen från insekter i näringsfattiga miljöer. De använder fortfarande fotosyntes.'],
['Specialist eller generalist?','En <b>specialist</b> är beroende av en viss sorts miljö eller föda. Lavskrikan är i bokens exempel knuten till gamla barrskogar. En <b>generalist</b>, som rödräven, kan äta många sorters mat och leva i flera miljöer.','Specialisering kan vara en fördel i en stabil miljö, men göra arten sårbar när just den miljön försvinner.']
]},
{id:'manniskan',name:'Människans utveckling',icon:'◎',color:'sand',pages:'Elevboken s. 20–21',intro:'Gemensamma förfäder, fria händer och samarbete.',cards:[
['En gren på livets träd','Människan tillhör primaterna och är ett däggdjur. Vi och andra nu levande apor har <b>gemensamma förfäder</b>. Våra närmaste nu levande släktingar är schimpanser och bonoboer.','Vi härstammar inte från dagens schimpanser. Våra utvecklingslinjer delades för ungefär 6–8 miljoner år sedan.'],
['Händer, ben och svett','Upprätt gång på två ben frigör händerna för att bära och använda verktyg. En tumme som kan möta fingrarna hjälper oss att gripa. Långa ben och förmågan att svettas hjälper oss att röra oss långt och bli av med värme.','Koppla alltid egenskapen till nyttan: ”Tummens placering gör att vi kan hålla och hantera verktyg.”'],
['Språk och samarbete','Människor kan samarbeta, planera och lära av varandra. Ett utvecklat språk gör det möjligt att dela kunskap och varna för faror. Framåtriktade ögon hjälper oss att bedöma avstånd.','På en resonemangsfråga finns ofta flera bra svar. Välj en anpassning och förklara varför den kan ha ökat chansen att överleva.'],
['Flera människoarter','Det har funnits flera människoarter. <b>Homo habilis</b> förknippas med tidiga stenverktyg och <b>Homo erectus</b> med användning av eld. Neandertalare levde samtidigt som vår art under en period.','Homo sapiens är vår art. Den uppstod i Afrika för ungefär 300 000 år sedan. Evolution är ett förgrenat träd, inte en stege med människan som mål.'],
['Lucy och släktskap','Lucy är ett berömt fossil av <b>Australopithecus</b>, omkring 3,2 miljoner år gammalt. Fossil av skelett kan visa till exempel hur tidiga släktingar gick. DNA ger andra ledtrådar om släktskapet.','Människor är en liten, ung gren i livets mycket långa historia.']
]},
{id:'ekosystem',name:'Ekosystem & näringsvävar',icon:'⌘',color:'mint',pages:'Elevboken s. 22–25',intro:'Vem äter vem – och vart tar energin vägen?',cards:[
['Mer än bara djur','Ett <b>ekosystem</b> är samspelet mellan allt levande och den icke-levande miljön på en plats. Där ingår till exempel växter, djur, svampar, vatten, ljus, temperatur och mark. Det kan vara en stubbe eller ett helt hav.','Levande: en mask. Icke-levande: vattnet, stenen och solljuset. Båda delarna påverkar livet.'],
['Mångfald på tre nivåer','<b>Biologisk mångfald</b> betyder variation av arter, variation inom arter och variation av ekosystem. Många individer behövs för livskraftiga populationer, men mångfald är mer än bara ett stort antal djur.','Stor mångfald kan hjälpa ett ekosystem att klara förändringar. Flera arter kan delvis fylla liknande roller.'],
['Näringskedjans roller','En <b>producent</b>, som en grön växt eller alg, bygger näring genom fotosyntes. En <b>konsument</b> får näring genom att äta andra organismer. En <b>toppkonsument</b> står högst i den kedja man visar.','Gräs → hare → räv. Pilen går från det som blir uppätet till den som äter. Den visar näringens och energins väg.'],
['Kedjor blir vävar','En näringskedja visar en förenklad väg. Många djur äter flera arter och äts av olika rovdjur. Flera sammanlänkade kedjor bildar en <b>näringsväv</b>. Förändringar kan därför sprida sig genom väven.','Färre gäddor kan ge fler småfiskar, medan ett djur som äter gäddor kan få mindre mat. Det är möjliga följder; en verklig väv har fler samband.'],
['Energi flödar – ämnen går runt','Solen är energikälla för de flesta ekosystem. Producenter lagrar energi i näring. Djur använder energi för rörelse, värme och tillväxt. Vid varje steg sprids energi som <b>värme</b>. Mindre energi finns kvar till nästa nivå.','En näringspyramid har därför en bred bas av producenter och färre toppkonsumenter. Energin återvinns inte i samma kretslopp som näringsämnena.'],
['Nedbrytare återför näring','Svampar, bakterier och smådjur hjälper till att bryta ner döda organismer och avfall. Mineralämnen kommer tillbaka till mark och vatten och kan tas upp av producenter igen.','Utan nedbrytare skulle dött material samlas och näringsämnen bli svårare för växterna att få tag på.'],
['Fyra olika livsmiljöer','<b>Tropisk regnskog:</b> mycket artrik.<br><b>Tundra:</b> kallt, kort sommar, mark med permafrost.<br><b>Ålgräsäng:</b> skydd och mat åt fiskyngel – havets barnkammare.<br><b>Djuphavskälla:</b> mörker; kemisk energi kan ligga till grund för näringskedjor.','Vid djuphavskällor kan bakterier använda kemisk energi. Jätterörmaskar får hjälp av sådana bakterier. Här behövs inte solljus som direkt energikälla.']
]},
{id:'havet',name:'Havet & älven',icon:'≈',color:'blue',pages:'Elevboken s. 26–27',intro:'Från solbelyst yta till mörka djup och laxens vandring.',cards:[
['Havet gör livet möjligt','Hav täcker mer än två tredjedelar av jordens yta. De tar upp värme och koldioxid. Alger och andra fotosyntetiserande organismer i havet står för ungefär hälften av jordens syreproduktion.','Havet innehåller många slags livsmiljöer och en stor mångfald av liv.'],
['Vid ytan','Solljus når havets översta delar. Där kan <b>växtplankton</b> utföra fotosyntes. Djurplankton äter växtplankton och blir i sin tur mat åt fiskar och andra djur.','Växtplankton → djurplankton → småfisk → större fisk. Plankton driver med vattnet.'],
['Längre ner','Där inget solljus når fram kan vanlig fotosyntes inte ske. Många djur får mat från organiskt material som sjunker från ytan, eller äter andra djur. Vissa kan skapa eget ljus.','I djuphavet måste organismer klara mörker, högt tryck, ofta kyla och liten tillgång på mat.'],
['Salt, sött och bräckt','Västkustens havsvatten är saltare än Östersjöns. <b>Bräckt vatten</b> är en blandning av saltvatten och sötvatten. Östersjön får sötvatten från älvar och har begränsat inflöde av saltvatten.','Därför kan vissa sötvattensarter och vissa saltvattensarter leva i Östersjön – om de klarar salthalten.'],
['Laxens väg hem','Många laxar växer till i havet och vandrar tillbaka till vattendraget där de föddes för att <b>leka</b>. Leka betyder här att föröka sig: lägga rom och befrukta den. Laxen behöver strömmande, syrerikt vatten med grus och sten.','Dammar kan stoppa vandringen. Fiskvägar och borttagna hinder kan hjälpa fisken att nå lekplatser.'],
['Älvens många liv','Älvar och deras stränder ger livsmiljöer åt fiskar, musslor, kräftdjur och växter. Växtlighet längs stranden ger skugga och skydd. En förändring i vattenflödet påverkar därför mer än bara fisken.','Resonera i flera led: damm → hinder för vandring → färre når lekplatsen → färre ungar kan födas.']
]},
{id:'natur',name:'Människan & naturen',icon:'✳',color:'peach',pages:'Elevboken s. 28–33',intro:'Naturens tjänster, störningar och hur vi hjälper till.',cards:[
['Vad är en ekosystemtjänst?','<b>Ekosystemtjänster</b> är nyttor vi människor får av naturen. Exempel är mat, dricksvatten, pollinering, rening av vatten och platser för återhämtning.','En jordbävning är inte en ekosystemtjänst. Att naturen ger oss rent vatten är det.'],
['Fyra grupper i boken','<b>Grundläggande:</b> processer som fotosyntes och näringsämnenas kretslopp.<br><b>Reglerande:</b> pollinering, vattenrening och rötter som håller jorden på plats.<br><b>Försörjande:</b> mat, dricksvatten och virke.<br><b>Sociala och kulturella:</b> bad, promenader, naturupplevelser och återhämtning.','Från ett träd: fotosyntes är grundläggande, rötternas skydd mot erosion reglerande, ved försörjande och en skön rastplats social/kulturell.'],
['Störningar i ekosystem','Stormar, översvämningar och bränder kan vara naturliga störningar. Människor orsakar också störningar, till exempel oljeutsläpp, avskogning och övergödning. Vissa störningar kan ha båda orsakerna.','En brand kan starta av blixten eller av en människa. Störningar kan ändra vilka arter som klarar sig.'],
['Övergödning i fyra led','<b>1.</b> För mycket näringsämnen når vattnet.<br><b>2.</b> Alger växer snabbt och vattnet blir grumligare.<br><b>3.</b> Döda alger bryts ner av nedbrytare.<br><b>4.</b> Nedbrytningen förbrukar syre och kan ge syrebrist som skadar djur.','Förväxla inte näring och syre. Mycket näring kan indirekt leda till lite syre.'],
['Främmande och invasiv','En främmande art har med människans hjälp kommit till ett område där den inte hör hemma naturligt. Om den sprider sig och skadar naturens mångfald kan den vara <b>invasiv</b>. Den kan konkurrera om plats och mat eller sprida sjukdomar.','Exempel från materialet är blomsterlupin, parkslide, jättebalsamin och signalkräfta. Alla främmande arter är inte invasiva.'],
['Skydda och återskapa','<b>Fridlysning</b> är ett lagligt skydd för arter. Naturreservat kan skydda livsmiljöer. Att återskapa natur kan vara att öppna vandringsvägar för fisk, återställa våtmarker eller sköta blomrika ängar.','Syftet med strandskydd i materialet är både livsmiljöer för växter och djur och människors tillgång till stränder. Resonera om naturvärden och möjligheten att bygga. Detaljregler ingår inte här.'],
['Allt hänger ihop','När mångfalden minskar kan ekosystem bli sårbarare och ge oss färre nyttor. Färre pollinerare kan till exempel påverka skörden. Bäverdammar kan skapa våtmarker, hålla kvar vatten och ge fler arter livsmiljöer.','Rachel Carson beskrev hur bekämpningsmedel som DDT skadade naturen. Vissa svårnedbrytbara gifter kan få högre koncentration längre upp i näringskedjan.'],
['Ta ställning med en förklaring','Ett bra resonemang har ett påstående, ett ”därför att” och en följd. Exempel: ”Vi bör bevara en blomrik äng eftersom pollinerare får mat där. Det kan hjälpa växter att bilda frön och ge oss frukt.”','Det går att diskutera flera perspektiv: natur, människors hälsa, energi och ekonomi. Förklara sambanden, inte bara vad du tycker.']
]}
];
const RAW_QUESTIONS = {
historia:[
['Ungefär hur gammal är jorden?','4,6 miljarder år','4,6 miljoner år','300 000 år','En miljard är tusen miljoner. Jorden är mycket äldre än livet på land.'],
['Hur såg de första livsformerna ut?','Encelliga organismer i vatten','Små däggdjur på land','Mossor i skogar','Det tidigaste livet bestod av enkla, encelliga organismer i vatten.'],
['Varför var tidiga bakteriers fotosyntes så viktig?','Den ökade mängden syre','Den tog bort allt vatten','Den bildade de första dinosaurierna','Fotosyntes frigör syre. Mer syre skapade möjligheter för fler livsformer.'],
['Vad består alla levande organismer av?','Celler','Bara vatten','Små organ med lungor','Encelliga organismer har en cell; flercelliga har många.'],
['Vilken grupp innehåller maneter och koraller?','Nässeldjur','Däggdjur','Svampdjur','Nässeldjur har nässelceller som kan fånga byten och ge skydd.'],
['Vad kom först på land enligt materialet?','Enkla växter, före landdjuren','Människor, före växterna','Däggdjur, före mossorna','Enkla växter etablerades på land innan djuren följde.'],
['Vad innebär det att en unge diar?','Den dricker mjölk från sin mamma','Den andas genom huden','Den äter bara frön','Däggdjurens ungar diar.'],
['Vad kunde hända när de stora dinosaurierna dog ut?','Däggdjur kunde spridas till fler livsmiljöer','De första cellerna uppstod','Allt liv på jorden försvann','Däggdjur fanns redan. Minskad konkurrens gav fler möjligheter att utvecklas och spridas.'],
['Vilken ordning är rimlig, från äldst till yngst?','Första celler → liv på land → Homo sapiens','Homo sapiens → första celler → liv på land','Liv på land → Homo sapiens → första celler','Det enkla livet i vatten är mycket äldre än livet på land och människan.'],
['Hur tog tidiga landlevande leddjur upp syre?','Genom små öppningar och rör i kroppen','Med fiskgälar som bara fungerar i luft','Genom att äta stenar','I materialet beskrivs små rör och öppningar som släpper in luft.']
],
evolution:[
['Vilket är ett exempel på evolution?','En ärftlig pälsfärg blir vanligare under många generationer','En hund lär sig sitta','En människa tränar upp sina muskler','Evolution gäller ärftliga förändringar i populationer över generationer.'],
['Vad är variation inom en art?','Skillnader mellan artens individer','Att alla individer är likadana','Att en individ byter art','Variation kan vara skillnader i färg, storlek eller andra egenskaper.'],
['Vad innebär naturligt urval?','Gynnsamma ärftliga egenskaper förs oftare vidare','Alla djur får de egenskaper de önskar','De största djuren överlever alltid','Egenskaper som passar miljön kan öka chansen att få överlevande ungar.'],
['Vilket namn förknippas med naturligt urval?','Charles Darwin','Rachel Carson','Homo erectus','Darwin är känd för teorin om evolution genom naturligt urval.'],
['Vilken näbb passar oftast bäst för hårda frön?','En kraftig näbb som kan knäcka frön','En mycket tunn näbb för små insekter','Alla näbbar fungerar exakt lika bra','Näbbens form påverkar vilken föda fågeln kan komma åt.'],
['Varför behövs ärftlig variation för naturligt urval?','Det måste finnas egenskaper som kan gynnas olika','Så att alla får lika många ungar','För att individer ska kunna välja sina gener','Olika egenskaper ger olika fördelar i en viss miljö.'],
['En fågelart möter kallare vintrar. Vad kan ske?','Köldtåliga individer får fler överlevande ungar','Varje fågel bestämmer sig för att få päls','Alla får genast exakt samma nya gen','Om köldtåligheten är ärftlig kan den bli vanligare efter flera generationer.'],
['Vilken förändring ingår i valarnas utveckling?','Framben blev fenor över generationer','Gälar blev lungor hos dagens valar','En val förlorar sina ben under sin egen livstid','Valar härstammar från landlevande däggdjur. De har fortfarande lungor.'],
['Betyder ”bäst anpassad” alltid ”starkast”?','Nej, rätt egenskap beror på miljön','Ja, muskelstyrka är det enda som räknas','Ja, alla stora djur får alltid flest ungar','Kamouflage, tålighet och förmåga att hitta mat kan vara viktigare än styrka.'],
['Vad kan många generationers förändring till slut leda till?','Att nya arter uppstår','Att alla arter blir människor','Att variation upphör överallt','Utvecklingslinjer kan bli så olika att nya arter bildas.']
],
dna:[
['Vad är en gen?','En del av DNA som bidrar till egenskaper','En hel bakterie','Ett fossil av ett djur','DNA innehåller många gener med information om funktioner och egenskaper.'],
['Varifrån kommer arvsmassan vid könlig fortplantning?','Från både ägget och spermien','Bara från spermien','Bara från maten mamman äter','Avkomman får genetiskt material från båda föräldrarna.'],
['Varför kan syskon vara olika?','De får olika kombinationer av gener','De tillhör alltid olika arter','De har inget DNA gemensamt','Slumpen påverkar vilka kombinationer av föräldrarnas gener ungarna får.'],
['Vad är en mutation?','En förändring i DNA','Ett medvetet val att ändra en egenskap','En organism som går i dvala','Mutationer kan vara neutrala, skadliga eller ibland gynnsamma.'],
['Vad menas med avel?','Människor väljer föräldrar för önskade egenskaper','Djur väljer att ändra sitt DNA','Fossil bryts ner i marken','Avel är ett urval som människor styr.'],
['Vad är ett fossil?','Bevarade rester eller spår av äldre liv','En levande bakterie','En särskild sorts DNA','Ben kan förstenas och avtryck kan bevaras. Båda kan vara fossil.'],
['Vad händer med kol-14 efter att organismen dött?','Mängden minskar med tiden','Mängden ökar hela tiden','Mängden blir genast exakt noll','Kol-14 sönderfaller. Hälften återstår efter ungefär 5 730 år.'],
['Varför används inte kol-14 för miljontals år gamla dinosauriefossil?','För lite kol-14 finns kvar för säker mätning','Dinosaurier hade inga celler','Kol-14 fungerar bara på levande djur','Gränsen är ungefär 50 000 år för daterbart organiskt material. Andra metoder behövs för äldre fynd.'],
['Varför använda både fossil och DNA?','De ger olika ledtrådar som kompletterar varandra','De visar alltid exakt samma sak','DNA visar bara hur ett djur såg ut','Fossil kan visa kroppsformer; DNA hjälper till att visa släktskap.'],
['Vilket påstående om mammutar stämmer?','De levde samtidigt som människor','De levde innan jorden bildades','De var fiskar med gälar','De sista mammutarna försvann för omkring 4 000 år sedan.'],
['Hur kan polisen använda DNA?','Jämföra biologiska spår med personers DNA','Läsa någons minnen ur ett hårstrå','Mäta ålder på fingeravtryck med kol-14','Blod och saliv kan innehålla celler med DNA som går att jämföra.']
],
anpassning:[
['Vad hjälper tumlaren att simma snabbt?','Strömlinjeformad kropp och kraftig stjärt','Tjocka ben och stora öron','En stor platt kropp utan fenor','Kroppsformen minskar motståndet i vattnet och stjärten ger kraft.'],
['Hur tar en fisk upp syre ur vattnet?','Med gälar','Med pälsen','Genom att svälja stenar','Gälarna tar upp syre som är löst i vattnet.'],
['Varför måste sälar komma upp till ytan?','De har lungor och andas luft','De har gälar som måste torka','De kan bara få mat ovanför ytan','Sälar är däggdjur med lungor, även om de lever mycket i vatten.'],
['Vad är kamouflage?','Att smälta in i omgivningen','Att alltid vara starkt färgad','Att sakna naturliga fiender','Kamouflage minskar risken att bli upptäckt.'],
['Vilket djur är växelvarmt?','Groda','Människa','Sparv','Grodans kroppstemperatur påverkas mycket av omgivningen.'],
['Vilken grupp är jämnvarm?','Fåglar och däggdjur','Alla fiskar och groddjur','Alla insekter och spindlar','Fåglar och däggdjur håller kroppstemperaturen relativt jämn.'],
['Vilken är en möjlig vinteranpassning?','Dvala som minskar energibehovet','Att sluta behöva energi helt','Att en fisk får päls varje vinter','Minskad aktivitet och dvala kan spara energi när det är kallt och ont om föda.'],
['Varför kan en specialist bli sårbar?','Den kan vara beroende av en viss miljö eller föda','Den kan alltid äta alla sorters mat','Den kan aldrig vara väl anpassad','Om den viktiga miljön eller maten försvinner kan specialisten få svårt att klara sig.'],
['Varför är rödräven en generalist?','Den kan äta olika saker och leva i olika miljöer','Den äter bara ett slags frö','Den lever bara i en enda gammal skog','Generalister har bredare möjligheter att hitta mat och livsmiljö.'],
['Vilken egenskap hjälper en näckros?','Långa stjälkar och luftkanaler som hjälper bladen nå ytan','Gälar som fångar fisk','Tjock vinterpäls','Vid vattenytan får bladen tillgång till ljus för fotosyntesen.']
],
manniskan:[
['Vilket påstående om människan och schimpansen stämmer?','De har gemensamma förfäder','Dagens schimpanser blir människor när de åldras','Människan är inte ett däggdjur','Våra utvecklingslinjer har utvecklats åt olika håll från gemensamma förfäder.'],
['Vad heter vår art?','Homo sapiens','Homo erectus','Australopithecus','Homo sapiens är den människoart som lever idag.'],
['När och var uppstod Homo sapiens ungefär?','För 300 000 år sedan i Afrika','För 4,6 miljarder år sedan i Europa','För 4 000 år sedan i Amerika','Vår art är mycket ung jämfört med jordens och livets historia.'],
['Vilken nytta har upprätt gång?','Händerna blir fria att bära och använda verktyg','Vi behöver inte längre mat','Vi kan andas under vatten','Tvåbent gång frigör händerna för andra uppgifter.'],
['Hur hjälper tummens placering oss?','Vi kan gripa och hantera föremål','Vi kan utföra fotosyntes','Vi får högre kroppstemperatur','Tummen kan möta fingrarna, vilket ger ett bra grepp.'],
['Vad kan ett utvecklat språk hjälpa oss med?','Att samarbeta, planera och dela kunskap','Att ändra våra gener med vilja','Att sluta vara beroende av naturen','Kunskap kan spridas mellan människor och generationer.'],
['Vem var Lucy?','En tidig människosläkting känd genom ett fossil','Den första moderna människan i Sverige','En forskare som uppfann kol-14','Lucy tillhörde Australopithecus och levde för ungefär 3,2 miljoner år sedan.'],
['Levde vår art samtidigt som andra människoarter?','Ja, bland annat neandertalare','Nej, aldrig','Bara samtidigt som dinosaurier för 100 miljoner år sedan','Under en period fanns flera människoarter samtidigt.'],
['Vilken nytta ger svettning?','Den hjälper kroppen att kylas när svetten avdunstar','Den gör oss växelvarma som grodor','Den ersätter behovet av vatten','Svettning hjälper oss att avge värme vid ansträngning och i värme.']
],
ekosystem:[
['Vad ingår i ett ekosystem?','Både levande organismer och den icke-levande miljön','Bara de stora djuren','Bara växter som människor planterat','Ljus, vatten och mark påverkar organismerna och ingår i samspelet.'],
['Vilka tre nivåer har biologisk mångfald?','Variation inom arter, mellan arter och mellan ekosystem','Bara stora, små och medelstora djur','Bara vatten, luft och sten','Mångfald handlar om både ärftlig variation, olika arter och olika livsmiljöer.'],
['Vilken organism är en producent?','En grön alg','En gädda','En räv','Algen kan tillverka näring med fotosyntes.'],
['Vad visar pilen i ”gräs → hare”?','Näring och energi går från gräset till haren','Gräset äter haren','Haren producerar solljus','Pilen går från maten till den som äter maten.'],
['Vad är en näringsväv?','Flera sammankopplade näringskedjor','En kedja med bara en art','Ett spindelnät som fångar solljus','Samma art kan ingå i flera kedjor eftersom den äter eller äts av flera arter.'],
['Vad gör nedbrytare?','Återför näringsämnen från dött material','Skapar ny solenergi','Stoppar alla kretslopp','Bakterier, svampar och smådjur hjälper till att återföra näring till mark och vatten.'],
['Varför finns mindre energi högre upp i näringspyramiden?','Energi används och sprids som värme i varje steg','Energin går i ett slutet kretslopp utan förlust','Rovdjur behöver ingen energi','Bara en del av energin blir kvar i biomassa som kan ätas på nästa nivå.'],
['Vad kan hända om gäddorna försvinner ur en sjö?','Småfisk kan öka och gäddätare få mindre mat','Inga andra arter kan påverkas','Alla producenter slutar genast växa','Arter hänger ihop i en näringsväv, så en förändring kan påverka flera led.'],
['Varför kallas ålgräsängar havets barnkammare?','Fiskyngel får mat och skydd där','Allt havsvatten föds där','Bara däggdjur lever där','Mellan bladen kan små fiskar gömma sig och växa.'],
['Var finns ofta permafrost?','På tundran','I tropisk regnskog','I grunda varma korallrev','Permafrost betyder att mark förblir frusen under lång tid.'],
['Vad kan vara energibas vid mörka djuphavskällor?','Bakterier som använder kemisk energi','Solljus från månen','Gräs som alltid måste nå ytan','Sådana ekosystem kan drivas av kemisk energi via bakterier.'],
['Vad cirkulerar i kretslopp i ekosystemet?','Näringsämnen','All energi utan att spridas','Solljuset i en sluten ring','Ämnen återanvänds. Energi flödar genom systemet och sprids till sist som värme.']
],
havet:[
['Vad är bräckt vatten?','En blandning av saltvatten och sötvatten','Vatten utan syre','Enbart mycket salt vatten','Östersjön har bräckt vatten med lägre salthalt än västkustens hav.'],
['Var i havet kan växtplankton utföra fotosyntes?','Där solljuset når fram','Bara på den mörkaste havsbottnen','Överallt, även utan ljus','Fotosyntes behöver ljusenergi.'],
['Vad äter djurplankton i en enkel näringskedja?','Växtplankton','Havsörnar','Stenar','Växtplankton är producenter och kan ätas av djurplankton.'],
['Varifrån kan djur i mörkare havsdjup få mat?','Sjunkande organiskt material och andra djur','Enbart genom vanlig fotosyntes','Genom att äta solljus','Rester från livet nära ytan kan sjunka ner och bli föda.'],
['Vilka förhållanden måste många djuphavsdjur klara?','Mörker, högt tryck och liten tillgång på mat','Mycket starkt solljus och torr luft','Inget tryck och inget vatten','På stora djup är det mörkt, ofta kallt och trycket är högt.'],
['Varför är Östersjön mindre salt än västkustens hav?','Älvar tillför sötvatten och saltvatteninflödet är begränsat','Allt salt äts upp av fiskar','Regn innehåller mer salt än havet','Blandningen och det begränsade utbytet ger bräckt vatten.'],
['Vad betyder det att laxen leker?','Den förökar sig genom rom och befruktning','Den tävlar om vem som simmar snabbast','Den går i vinterdvala','”Lek” är fiskarnas fortplantning.'],
['Vart vandrar många laxar när de ska leka?','Tillbaka till vattendraget där de föddes','Till det djupaste havet','Upp på land för att bygga bon','De söker lämpliga lekplatser i strömmande, syrerikt sötvatten.'],
['Hur kan en fiskväg hjälpa laxen?','Den kan göra det möjligt att passera ett vandringshinder','Den gör laxen oberoende av syre','Den förvandlar saltvatten till föda','Dammar kan spärra vägen mellan havet och lekplatserna.']
],
natur:[
['Vilket är en ekosystemtjänst?','Bin som pollinerar fruktträd','Ett oljeutsläpp','En jordbävning','Pollineringen hjälper växter att bilda frön och frukter, vilket vi har nytta av.'],
['Vilken grupp hör mat och virke till?','Försörjande tjänster','Sociala och kulturella tjänster','Bara störningar','Det är resurser som vi får från naturen.'],
['Vilken grupp hör en skogspromenad för återhämtning till?','Sociala och kulturella tjänster','Försörjande tjänster','Invasiva tjänster','Naturupplevelser kan ge välbefinnande, glädje och återhämtning.'],
['Vilken grupp hör fotosyntes till i bokens indelning?','Grundläggande tjänster','Bara sociala tjänster','Störningar','Fotosyntesen är en process som ligger till grund för många andra nyttor.'],
['Vilken är en reglerande tjänst?','Rötter som håller jorden på plats','Virke att bygga med','En vacker utsikt att njuta av','Rötterna kan minska erosion. Pollinering och vattenrening är andra exempel.'],
['Vilken ordning beskriver övergödning?','Mer näring → fler alger → nedbrytning → syrebrist','Mindre näring → mer solljus → fler stenar','Mer syre → färre alger → ingen nedbrytning','Nedbrytare använder syre när de bryter ner stora mängder döda alger.'],
['Vad skiljer en invasiv art från enbart en främmande art?','Den sprider sig och orsakar skada på naturens mångfald','Den måste vara ett rovdjur','Den måste vara större än alla inhemska arter','Alla främmande arter orsakar inte skada. Invasiva kan tränga undan andra arter.'],
['Vilken störning kan orsakas både av naturen och människor?','Skogsbrand','Bara ett fabriksutsläpp','Avel av hundar','En brand kan starta med ett blixtnedslag eller genom människors handlingar.'],
['Vad är syftet med fridlysning?','Att skydda växt- och djurarter','Att göra det lättare att skada sällsynta arter','Att hindra alla djur från att föröka sig','Fridlysning ger arter skydd. Exakta regler kan skilja sig mellan arter.'],
['Vilket är ett sätt att återskapa natur?','Återställa en våtmark eller öppna en fiskväg','Släppa ut mer olja i havet','Ta bort alla blommande växter','Åtgärder kan återge arter livsmiljöer och möjligheter att föröka sig.'],
['Varför kan minskad biologisk mångfald påverka oss?','Viktiga funktioner som pollinering kan försämras','Vi slutar behöva mat','Naturen ger oss automatiskt fler tjänster','Vi är beroende av fungerande ekosystem för bland annat mat, vatten och återhämtning.'],
['Vad uppmärksammade Rachel Carson?','Att bekämpningsmedel kunde skada djur och näringskedjor','Att alla gifter försvinner när ett djur äter','Att fotosyntes bara sker på land','Hon bidrog till förståelsen för hur miljögifter kan påverka flera delar av naturen.']
]
};
const QUESTIONS=Object.entries(RAW_QUESTIONS).flatMap(([topic,rows])=>rows.map((r,i)=>({id:`${topic}-${i}`,topic,q:r[0],options:r.slice(1,4),answer:0,why:r[4]})));
const TERMS=[
['Art','En grupp organismer som vanligtvis kan få fertil avkomma tillsammans. Det betyder att ungarna i sin tur kan få egna ungar.','evolution'],
['Cell','Livets minsta levande byggsten. Alla organismer består av en eller flera celler.','historia'],
['Bakterie','En encellig organism utan cellkärna.','historia'],
['Fotosyntes','Med ljusenergi byggs druvsocker av koldioxid och vatten. Syre frigörs.','historia'],
['Evolution','Förändring av ärftliga egenskaper i grupper av organismer över generationer.','evolution'],
['Naturligt urval','Individer med ärftliga egenskaper som passar miljön får oftare överlevande avkomma.','evolution'],
['Variation','Skillnader mellan individer inom samma art.','evolution'],
['Anpassning','En egenskap som hjälper en organism att klara sin livsmiljö.','anpassning'],
['DNA','Molekyler som bär organismens ärftliga information.','dna'],
['Gen','En del av DNA som bidrar till en egenskap eller funktion.','dna'],
['Mutation','En förändring i DNA. Den kan vara neutral, skadlig eller gynnsam.','dna'],
['Avel','När människor väljer vilka individer som får föröka sig för att få önskade egenskaper.','dna'],
['Fossil','Bevarade rester eller spår av organismer som levde förr.','dna'],
['Kol-14-metoden','Åldersbestämning av organiskt material genom att mäta kvarvarande kol-14, vanligen upp till cirka 50 000 år.','dna'],
['Kamouflage','Färg eller form som gör en organism svår att upptäcka i sin omgivning.','anpassning'],
['Växelvarm','Kroppstemperaturen påverkas mycket av omgivningens temperatur. Exempel: groda.','anpassning'],
['Jämnvarm','Håller en relativt jämn kroppstemperatur. Fåglar och däggdjur är jämnvarma.','anpassning'],
['Dvala','En period med mycket låg aktivitet och sänkt ämnesomsättning som sparar energi.','anpassning'],
['Specialist','Art som är beroende av en begränsad sorts föda eller livsmiljö.','anpassning'],
['Generalist','Art som kan använda många sorters föda eller leva i flera miljöer.','anpassning'],
['Homo sapiens','Det vetenskapliga namnet på vår människoart.','manniskan'],
['Däggdjur','Djur med hår eller päls där ungarna får mjölk från mamman.','historia'],
['Ekosystem','Samspelet mellan organismer och den icke-levande miljön på en plats.','ekosystem'],
['Biologisk mångfald','Variation inom arter, mellan arter och mellan ekosystem.','ekosystem'],
['Producent','Organism som bygger sin egen organiska näring, oftast med fotosyntes.','ekosystem'],
['Konsument','Organism som får näring och energi genom att äta andra organismer.','ekosystem'],
['Toppkonsument','Konsument högst upp i den näringskedja man beskriver.','ekosystem'],
['Nedbrytare','Organismer som bryter ner dött material och återför näringsämnen.','ekosystem'],
['Näringskedja','En förenklad följd som visar hur näring och energi går från mat till den som äter.','ekosystem'],
['Näringsväv','Flera näringskedjor som hänger ihop.','ekosystem'],
['Näringspyramid','Bild som visar olika näringsnivåer och att mindre energi finns kvar högre upp.','ekosystem'],
['Bräckt vatten','Vatten med en salthalt mellan sötvatten och havsvatten, som i Östersjön.','havet'],
['Plankton','Små organismer som driver med vattnet. Växtplankton fotosyntetiserar; djurplankton äter andra organismer.','havet'],
['Lek','Fiskars fortplantning, när rom läggs och befruktas.','havet'],
['Ekosystemtjänst','En nytta som människor får från naturen, till exempel pollinering eller mat.','natur'],
['Störning','En händelse eller påverkan som förändrar ett ekosystem, till exempel brand eller förorening.','natur'],
['Övergödning','För mycket näring i vatten eller mark. I vatten kan det ge algtillväxt och sedan syrebrist.','natur'],
['Invasiv främmande art','En art som förts till ett nytt område med människans hjälp och sprider sig så att naturens mångfald skadas.','natur'],
['Fridlysning','Ett rättsligt skydd för växt- och djurarter.','natur'],
['Återskapa natur','Återställa förutsättningar för naturliga miljöer, till exempel våtmarker och fria vattenvägar.','natur']
].map(([term,definition,topic],i)=>({id:`term-${i}`,term,definition,topic}));
const REASONING=[
{topic:'evolution',q:'Det blir mindre snö där en harart lever. Förklara hur brun vinterpäls kan bli vanligare över lång tid.',points:['Det finns ärftlig variation i pälsfärg.','Brun färg kan ge bättre kamouflage mot snöfri mark.','Bättre kamouflage kan ge större chans att överleva och få ungar.','Egenskapen förs vidare och blir vanligare över generationer.'],sample:'Om några harar har ärftliga egenskaper som ger brunare vinterpäls kan de vara svårare för rovdjur att se på snöfri mark. De kan då få fler överlevande ungar som ärver egenskapen. Efter många generationer kan brun päls bli vanligare.'},
{topic:'ekosystem',q:'Varför är nedbrytare viktiga, och varför behövs ändå ny energi från solen?',points:['Döda organismer och avfall bryts ner.','Näringsämnen återgår till mark och vatten och tas upp av producenter.','Energi sprids som värme och återvinns inte i samma kretslopp.','Solen tillför ny energi som fångas med fotosyntes.'],sample:'Nedbrytare frigör näringsämnen från dött material så att växter kan använda dem igen. Ämnena går runt, men energi sprids som värme i varje steg. Därför behöver de flesta ekosystem ett nytt inflöde av solenergi.'},
{topic:'natur',q:'Gödsel från en åker sköljs ut i en sjö. Förklara hur det kan leda till att fiskar dör.',points:['Gödseln tillför extra näringsämnen.','Algerna kan växa snabbt.','Döda alger bryts ner och nedbrytarna förbrukar syre.','Syrebrist kan skada eller döda fiskar.'],sample:'Den extra näringen kan ge kraftig algtillväxt. När algerna dör bryts de ner av nedbrytare som använder syre. Syret kan då bli så lågt att fiskarna inte klarar sig.'},
{topic:'anpassning',q:'Välj ett djur och en växt. Beskriv en anpassning hos varje och förklara nyttan.',points:['Ett namngivet djur och en konkret egenskap.','En förklaring till hur egenskapen hjälper djuret.','En namngiven växt och en konkret egenskap.','En förklaring till hur egenskapen hjälper växten.'],sample:'Gräsanden har simhud mellan tårna som hjälper den att paddla. Näckrosen har långa stjälkar och luftkanaler som hjälper bladen att nå vattenytan och solljuset. Andra väl förklarade exempel fungerar också.'},
{topic:'havet',q:'Varför kan en damm påverka både laxen och andra delar av ekosystemet?',points:['Dammen kan hindra laxens vandring.','Färre laxar kan nå lekplatser och få ungar.','Arter i näringsväven kan påverkas av förändrad tillgång på lax.','Fiskvägar eller borttagna hinder kan hjälpa.'],sample:'Om dammen stoppar laxen kan färre nå sitt lekvatten. Då kan antalet ungar minska och arter som äter lax påverkas. En fiskväg kan underlätta vandringen, och ett borttaget hinder kan återställa kontakten mellan miljöer.'},
{topic:'natur',q:'Ge en fördel och en nackdel med att skydda en strand från bebyggelse. Motivera sedan din ståndpunkt.',points:['En fördel för livsmiljöer eller tillgång till natur.','En nackdel, till exempel begränsad möjlighet att bygga.','En förklaring av följderna.','En egen ståndpunkt med motivering.'],sample:'Ett skydd kan bevara livsmiljöer och ge människor tillgång till stranden. Samtidigt kan en markägare få mindre möjlighet att bygga. Jag tycker att naturvärdena väger tungt eftersom förstörda livsmiljöer kan vara svåra att återskapa. En annan ståndpunkt kan också vara väl motiverad.'},
{topic:'dna',q:'Hur kompletterar fossil och DNA varandra när forskare undersöker evolution?',points:['Fossil ger spår av tidigare liv.','Fossil kan visa kroppsformer och förändringar över tid.','DNA kan jämföras för att undersöka släktskap.','Flera slags ledtrådar ger en bättre underbyggd bild.'],sample:'Fossil visar hur utdöda organismer kunde se ut. Genom att jämföra DNA kan forskare undersöka släktskap mellan organismer. Tillsammans ger de fler ledtrådar om livets utveckling än en metod ensam.'},
{topic:'manniskan',q:'Vilka två mänskliga anpassningar tror du har varit viktiga för överlevnaden? Förklara.',points:['Två konkreta egenskaper nämns.','Nyttan av den första egenskapen förklaras.','Nyttan av den andra egenskapen förklaras.','Egenskaperna kopplas till att klara miljön och överleva.'],sample:'Upprätt gång frigör händerna så att människor kan bära mat och använda redskap. Språk och samarbete hjälper oss att dela kunskap, planera och varna varandra. Det kan öka chansen att klara svårigheter.'}
];
